app/views/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from app.service import auth_service
import tweepy,time
from app.userdb import get_db,close_db
from app.function import like_tweepy,get_sorted_df,get_grouped_df,get_profile,retweet_tweepy,follow_tweepy,like_tweepy
from werkzeug.security import generate_password_hash, check_password_hash
import pandas as pd
from flask_login import LoginManager, login_user, logout_user, login_required, UserMixin

auth = Blueprint('auth', __name__)

@auth.route('/')
# @login_required
def index():
    if 'username' in session:
        return render_template('tweet/index.html',
            query = "?",
            count = "?"
            )
    else:
        return render_template('auth/login.html')

@auth.route('/logout', methods=['GET', 'POST'])
def logout():
    session.pop('username', None)
    session.pop('user_id', None)
    return redirect(url_for('auth.index'))

# signupページと、postするページを共通化。
@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'GET':
        return render_template('auth/signup.html')
    else:
        user = auth_service.signup(request.form)
        if user:
            flash('このユーザー名は既に登録されています。')
            return redirect(url_for('index'))
        flash('新規登録に成功しました。')
        return redirect(url_for('index'))
 
 
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('auth/login.html')
    else:
        user = auth_service.login(request.form)
        if not user:
            flash('メールアドレスもしくはパスワードに誤りがあります。')
            return render_template('auth.login')
        flash('ログインしました。')
        return redirect(url_for('index'))
    
@auth.route('/create_user', methods = ["GET","POST"])
def create_user():
    return render_template('auth/create_user.html')

@auth.route('/login4', methods = ["GET" , "POST"])
def login4():
    if request.method == 'POST':
        try:
            # global username,password,CONSUMER_KEY,CONSUMER_SECRET,ACCESS_TOKEN,ACCESS_SECRET
            username = request.form['username']
            password = request.form['password']
            CONSUMER_KEY  = request.form['ck']
            CONSUMER_SECRET = request.form['cs']
            ACCESS_TOKEN = request.form['at']
            ACCESS_SECRET = request.form['ats']
            return render_template(
            'auth/check.html',
            username=username,
            password=password,
            ck=CONSUMER_KEY,
            cs=CONSUMER_SECRET,
            at=ACCESS_TOKEN,
            ats=ACCESS_SECRET
            )

        except Exception as e:
            print(e)
            return render_template(
            'auth/create_user.html'
            )
    else:
        return render_template('auth/create_user.html')

@auth.route('/login2', methods = ["GET" , "POST"])
def login2():
    if request.method == 'POST':
        try:
            db = get_db()
            username = request.form['username']
            password = request.form['password']
            CONSUMER_KEY  = request.form['ck']
            CONSUMER_SECRET = request.form['cs']
            ACCESS_TOKEN = request.form['at']
            ACCESS_SECRET = request.form['ats']
            db.execute("INSERT INTO user (username,password) values(?,?)", (username,generate_password_hash(str(password), method='sha256')))
            db.execute("INSERT INTO api (ck,cs,at,ats) values(?,?,?,?)", (CONSUMER_KEY,CONSUMER_SECRET,ACCESS_TOKEN,ACCESS_SECRET))
            # #tweepy
            # auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
            # auth.set_access_token(ACCESS_TOKEN, ACCESS_SECRET)
            # #グローバル変数
            # global api
            # #APIインスタンスを作成
            # api = tweepy.API(auth)
            db.commit()
            close_db()
        # index.html をレンダリングする
            return render_template('auth/login.html')

        except Exception as e:
            print(e)
            message = "そのusernameはすでに使われております"
            username = request.form['username']
            password = request.form['password']
            CONSUMER_KEY  = request.form['ck']
            CONSUMER_SECRET = request.form['cs']
            ACCESS_TOKEN = request.form['at']
            ACCESS_SECRET = request.form['ats']
            return render_template(
            'auth/create_user2.html',
            message=message,
            username=username,
            password=password,
            ck=CONSUMER_KEY,
            cs=CONSUMER_SECRET,
            at=ACCESS_TOKEN,
            ats=ACCESS_SECRET
            )
    else:
        return render_template('auth/login.html')

@auth.route('/login3', methods = ["GET" , "POST"])
def login3():
    return render_template(
    'auth/create_user2.html',
    username=username,
    password=password,
    ck=CONSUMER_KEY,
    cs=CONSUMER_SECRET,
    at=ACCESS_TOKEN,
    ats=ACCESS_SECRET
    )

app/views/users.py
from flask import(
Blueprint,render_template,request,session,redirect, url_for,
)
import tweepy,time
from app.userdb import get_db,close_db
from app.function import like_tweepy,get_sorted_df,get_grouped_df,get_profile,retweet_tweepy,follow_tweepy,like_tweepy,getTweetBySearch,sessget
from werkzeug.security import generate_password_hash, check_password_hash
import pandas as pd
from flask_login import LoginManager, login_user, logout_user, login_required, UserMixin

users = Blueprint('users', __name__)
@users.route('/tweet', methods = ["GET" , "POST"])
def tweet():
    if request.method == 'POST':
        try:
            db = get_db()
            d = db.cursor()
            error_message = None
            # pass1=[]
            # user1=[]
            username  = request.form['username']
            password = request.form['pass']
            user = d.execute(
                'SELECT * FROM user WHERE username = ?', (username,)
            ).fetchone()
            if user is None:
                error_message = 'ユーザー名が正しくありません'
            elif not check_password_hash(user['password'], password):
                error_message = 'パスワードが正しくありません'
            
            if error_message is not None:
                # エラーがあればそれを表示したうえでログイン画面に遷移
                return render_template(
                'auth/login.html',
                message2=error_message
                )
            session["user_id"] = user["id"]
            session["username"] = user["username"]
            db.commit()
            close_db()
            return redirect(url_for('auth.index'))

        except Exception as e:
            print(e)
            message2 = "usernameが間違っております"
            return render_template(
            'auth/login.html',
            message2 = message2
            )
    else:
        return render_template('auth/login.html')

@users.route('/tweetaction', methods =["GET","POST"])
def tweetaction():
    if request.method == 'POST':
       query = request.form['query']# formのname = "query"を取得
       cnt = int(request.form['count'])
       button = request.form['button']
       userid = session["user_id"]
       api = sessget(userid)
       posts = []
       try:
           if button == "like":
               posts = like_tweepy(userid,query,cnt,api,posts)
           if button == "retweet":
               posts = retweet_tweepy(userid,query,cnt,api,posts)
           if button == "follow":
               posts = follow_tweepy(userid,query,cnt,api,posts)
           # grouped_df = get_grouped_df(tweets_df)
           # sorted_df = get_sorted_df(tweets_df)
           # 送られてきたものを返すしなきゃ返されない
           return render_template(
               'tweet/index.html',
               query = query,
               count = cnt,
               # profile=get_profile(user_id),
               posts = posts
               # grouped_df = grouped_df,
               # sorted_df = sorted_df
               )
       except Exception as e:
            print(e)
            messages = "APIが違います"
            title = "APIエラー"
            return render_template(
            'auth/login.html',
            message2 = messages,
            title = title
            )

    else:
            return render_template('index.html')

@users.route('/searchtweet', methods =["GET","POST"])
def search_tweet():
    return render_template('tweet/search_tweet.html')

@users.route('/search_tweet2', methods =["GET","POST"])
def search_tweet2():
    if request.method == 'POST':
       query = request.form['query']
       cnt = int(request.form['count'])
       button = request.form['button']
       startdate = request.form['startdate']
       enddate = request.form['enddate']
       posts2 = []
       userid = session["user_id"]
       api = sessget(userid)
       try:
           if button == "search":
               posts2 = getTweetBySearch(userid, query, startdate, enddate, cnt, api, posts2)
           # 送られてきたものを返すしなきゃ返されない
           return render_template(
               'tweet/search_tweet.html',
               yydd1 = startdate,
               yydd2 = enddate,
               word = query,
               posts2 = posts2
               )
       except Exception as e:
            print(e)
            messages = "APIが違います"
            title = "APIエラー"
            return render_template(
            'auth/login.html',
            message2 = messages,
            title = title
            )

    else:
            return render_template('index.html')

@users.route('/logcheck', methods =["GET","POST"])
def logcheck():
    db = get_db()
    c = db.cursor()
    datas=[]
    c.execute("select * from tweet")
    userid = session["user_id"]
    # print(userid)
    for d3 in c:
        data = {}
        if(d3["id"] == userid):
            data["created_at"] = str(d3["created_at"])
            data["text"] = str(d3["text"])
            data["user_id"] = str(d3["user_id"])
            data["fav"] = str(d3["fav"])
            data["retweet"] = str(d3["retweet"])
            data["action"] = str(d3["action"])
            datas.append(data)
    close_db()
    return render_template(
    'tweet/logcheck.html',
    posts=datas
    )

@users.route('/anary', methods =["GET","POST"])
def anarylog():
    # db = get_db()
    # c = db.cursor()
    # datas=[]
    # c.execute("select * from tweet")
    # for d3 in c:
    #     data = {}
    #     if(d3["id"]==id):
    #         print(str(d3["created_at"]))
    #         data["created_at"] = str(d3["created_at"])
    #         data["text"] = str(d3["text"])
    #         data["user_id"] = str(d3["user_id"])
    #         data["fav"] = str(d3["fav"])
    #         data["retweet"] = str(d3["retweet"])
    #         data["action"] = str(d3["action"])
    #         datas.append(data)
    # close_db()
    return render_template(
    'tweet/anary.html',
    # posts=datas
    )

columns = [
   "tweet_id",
   "created_at",
   "text",
   "fav",
   "retweets"
   ]

@users.route('/anary2', methods = ["GET" , "POST"])
def anary2():
   if request.method == 'POST':
       user_id = request.form['user_id']
       tweets_df = get_tweets_df(user_id)
       grouped_df = get_grouped_df(tweets_df)
       sorted_df = get_sorted_df(tweets_df)
       sorted_df2 = get_sorted_df2(tweets_df)
       return render_template(
           'tweet/anary.html',
           profile=get_profile(user_id),
           tweets_df = tweets_df,
           grouped_df = grouped_df,
           sorted_df = sorted_df,
           sorted_df2 = sorted_df2
           )
   else:
       return render_template('tweet/anary.html')

@users.route('/anary3', methods = ["GET" , "POST"])
def anary3():
   if request.method == 'POST':
       user_id = request.form['user_id']
       tweets_df = get_tweets_df(user_id)
       grouped_df = get_grouped_df(tweets_df)
       sorted_df = get_sorted_df(tweets_df)
       sorted_df2 = get_sorted_df2(tweets_df)
       return render_template(
           'tweet/anary.html',
           profile=get_profile(user_id),
           tweets_df = tweets_df,
           grouped_df = grouped_df,
           sorted_df = sorted_df,
           sorted_df2 = sorted_df2
           )
   else:
       return render_template('tweet/anary.html')

def get_tweets_df(user_id):
   userid = session["user_id"]
   api = sessget(userid)
   tweets_df = pd.DataFrame(columns=columns) #1
   for tweet in tweepy.Cursor(api.user_timeline,screen_name = user_id, exclude_replies = True).items(): #2
       try:
           if not "RT @" in tweet.text: #3
               se = pd.Series([ #4
                       tweet.id,
                       tweet.created_at,
                       tweet.text.replace('\n',''),
                       tweet.favorite_count,
                       tweet.retweet_count
                   ]
                   ,columns
                   )
               tweets_df = tweets_df.append(se,ignore_index=True) #5
       except Exception as e:
           print (e)
   tweets_df["created_at"] = pd.to_datetime(tweets_df["created_at"]) #6
   return tweets_df #7

def get_profile(user_id):
   userid = session["user_id"]
   api = sessget(userid)
   user = api.get_user(screen_name= user_id) #1
   profile = { #2
       "id": user.id,
       "user_id": user_id,
       "image": user.profile_image_url,
       "description": user.description # 自己紹介文の取得
   }
   return profile #3

def get_grouped_df(tweets_df):
   grouped_df = tweets_df.groupby(tweets_df.created_at.dt.date).sum().sort_values(by="created_at", ascending=False)
   return grouped_df

def get_sorted_df(tweets_df):
   sorted_df = tweets_df.sort_values(by="fav", ascending=False)
   return sorted_df

def get_sorted_df2(tweets_df):
   sorted_df = tweets_df.sort_values(by="retweets", ascending=False)
   return sorted_df


# @bp.route('/anary', methods =["GET","POST"])
# def anary():
#     db = get_db()
#     c = db.cursor()
#     datas=[]
#     c.execute("select * from tweet")
#     for d3 in c:
#         data = {}
#         if(d3["id"]==id):
#             print(str(d3["created_at"]))
#             data["created_at"] = str(d3["created_at"])
#             data["text"] = str(d3["text"])
#             data["user_id"] = str(d3["user_id"])
#             data["fav"] = str(d3["fav"])
#             data["retweet"] = str(d3["retweet"])
#             data["action"] = str(d3["action"])
#             datas.append(data)
#     close_db()
#     return render_template(
#     'anary.html',
#     posts=datas
#     )
#
# @bp.route('/tweetlog', methods = ["GET" , "POST"])
# def tweetlog():
#    if request.method == 'POST':
#        user_id = request.form['user_id'] # formのname = "user_id"を取得
#        return render_template('anary.html', user_id = user_id)
#    else:
#        return render_template('anary.html')

app/templates/tweet/index.html
<!DOCTYPE html><html lang="ja">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- ファビコン -->
<link rel="icon" href="/favicon-2.ico">
<title>TweetLiker</title>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css";; rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
<!-- [if lt IE 9]>
       <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>;;
       <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>;;
<![endif]-->
<style>
  body{
  background-color:#e6ecf0;
  }
  div{
  line-height: 1.2;
  }
  .white-container{
  border-bottom: 1px solid #e6ecf0;
  padding:20px;
  background-color:#ffffff;
  }
  #tweet-text{
  padding:20px;
  margin-bottom:10px;
  line-height: 1.2;
  }
  .hh1{
  color: #007bff !important;
  }
</style>
</head>
<body>
<div class="container">
 <div class="row">
   <div class="col-md-12">
    <h1 class="hh1"> <a href="{{url_for('auth.index')}}">Tweetliker</a></h1>
    <p>調べたい言葉を入れると関連するツイートに三つのアクションをする。</p>
    <p>※カウント数はその時点で可能な数のツイートに対してのみ適応されます</p>
    <form class="form-inline" action = "{{url_for('users.logcheck')}}" method="post">
      <button type="submit" name="button" value="alltweet">今ままでのlog確認</button>
    </form>
    <form class="form-horizontal" action = "{{url_for('users.search_tweet')}}" method="post">
      <button type="submit" name="button" value="searchtweet">Twitterの検索</button>
    </form>
    <form class="form-inline" action = "{{url_for('users.anarylog')}}" method="post">
    <button type="submit" name="button" value="anary">ユーザーの分析する</button>
    </form>
    <form class="form-inline" action = "{{url_for('auth.logout')}}" method="post">
    <button type="submit" name="button" value="logout">ログアウトする</button>
    </form>
    <!-- コードを追加 返信が来たかどうかの確認-->
    {% if query,count %}
      <p>{{query,count}}</p>
    {% endif %}
    <!---->
    <form class="form-horizontal" action = "{{url_for('users.tweetaction')}}" method="post">
       <div class="form-group">
          <label class="sr-only" for="query"></label>
          <div class="input-group">
             <span class="input-group-addon">キーワード</span>
             <input id=query name="query" placeholder="ここに興味のあるキーワードを入力してください。" type="text" class="form-control" required/>
          </div>
       </div>
       <div class="form-group">
          <div class="input-group">
             <span class="input-group-addon">最大何回そのアクションを行う？</span>
             <input id="count" name="count" placeholder="何個" type="number" class="form-control"required/>
          </div>
       </div>
       <div class="form-group">
       <button type="submit" class="btn btn-danger" name="button" value="like" id="2">いいねする</button>
       <button type="submit" class="btn btn-info" name="button" value="follow" id="3">フォローする</button>
       <button type="submit" class="btn btn-primary" name="button" value="retweet" id="4">リツイートする</button>
       </div>
    </form>
  </div>
 </div>
 <div class= "col-md-11">
   {% if posts %}
    {% for post in posts %}
    <div>{{post["select"]}}したツイート</div>
     <div class="white-container">
       <div>{{post["created_at"]}}</div>
       <form class="form-horizontal" action = "{{url_for('users.anary3')}}" method="post">
       <button type="submit" name="user_id" value={{post["user_id"]}}>ユーザー名:{{post["user_id"]}}</button>
       </form>
       <div id="tweet-text">{{post["text"]}}</div>
       <div>
         <span><i class="far fa-heart"></i>  {{post["fav"]}}</span> <span><i class="fas fa-retweet"></i>  {{post["retweet"]}}</span>
         <a class="pull-right" href="https://twitter.com/{{post["user_id"]}}" target="_blank">ユーザーのアカウント</a> -->
       </div>
     </div>
    {% endfor %}
   {% endif %}
 </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<script>
 {% if profile %}
  // bar chart data
  var barData = {
  labels : [{% for index, row in tweets_df.sort_values(by="created_at", ascending=True).iterrows() %}
                 "{{row['created_at']}}",
             {% endfor %}],
  datasets : [
     {
           label: "Retweets",
           backgroundColor: 'rgba(255, 99, 132, 0.2)',
           borderColor: 'rgba(255,99,132,1)',
           borderWidth:10,
           bezierCurve : false,
           data : [{% for index, row in tweets_df.sort_values(by="created_at", ascending=True).iterrows() %}
                     {{row["retweets"]}},
                   {% endfor %}]
     },{
           label: "Favorites",
           data : [{% for index, row in tweets_df.sort_values(by="created_at", ascending=True).iterrows() %}
                     {{row["fav"]}},
                   {% endfor %}],
           type: 'line',
           borderColor: 'rgb(63, 127, 191)',
     }
     ]
  }
  // draw bar chart
 var mychart = document.getElementById("chart");
 var chart = new Chart(mychart, {
   type:'bar',
   data:barData,
   options: {
       scales: {
         yAxes: [
           {
             ticks: {
               beginAtZero: true,
               min: 0,
               max: 1000
             }
           }
         ]
       }
     }
 });
 {% endif %}
</script>
</body>
</html>

app/templates/tweet/search_tweet.html
<!DOCTYPE html><html lang="ja">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- ファビコン -->
<link rel="icon" href="/favicon-2.ico">
<title>TweetLiker</title>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css";; rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
<!--
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>;;
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>;;
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" />
!-->
<script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP" crossorigin="anonymous"></script>
</head>
<style>
  body{
  background-color:#e6ecf0;
  }
  div{
  line-height: 1.2;
  }
  .white-container{
  border-bottom: 1px solid #e6ecf0;
  padding:20px;
  background-color:#ffffff;
  }
  #tweet-text{
  padding:20px;
  margin-bottom:10px;
  line-height: 1.2;
  }
  .hh1{
  color: #007bff !important;
  }
</style>

<body>
<div class="container">
 <div class="row">
   <div class="col-md-12">
    <h1 class="hh1"> <a href="{{url_for('auth.index')}}">Tweetliker</a></h1>
    <p>調べたい期間と検索したいワードを入力してください</p>
    <p>※カウント数はその時点で可能な数のツイートに対してのみ適応されます</p>
    <form class="form-inline" action = "{{url_for('users.anarylog')}}" method="post">
    <button type="submit" name="button" value="anary">ユーザーの分析する</button>
    </form>
    <!-- コードを追加 返信が来たかどうかの確認-->
    {% if yydd1,yydd2,word %}
     <p>{{yydd1}}〜{{yydd2}},検索ワード:{{word}}</p>
    {% endif %}
    <!---->
    <form class="form-horizontal" action = "{{url_for('users.search_tweet2')}}" method="post">
       <div class="form-group">
          <label class="sr-only" for="query"></label>
          <div class="input-group">
             <span class="input-group-addon">キーワード</span>
             <input id="query" name="query" placeholder="検索するキーワードを入力してください。" type="text" class="form-control" required/>
          </div>
       </div>
       <div class="form-group">
          <div class="input-group">
             <span class="input-group-addon">何個まで検索する</span>
             <input id="count" name="count" placeholder="何個" type="number" class="form-control"required/>
          </div>
       </div>
       <div class="form-group">
        <div class="input-group">
       <!-- コードを追加 返信が来たかどうかの確認
          <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
          -->
            <span class="input-group-addon">開始期間</span>
            <input id="date" type="text" name="startdate" class="form-control" placeholder="いつから yyyy-mm-dd" required/>
            <!-- コードを追加 返信が来たかどうかの確認
            <div class="input-group-append" data-target="#datetimepicker" data-toggle="datetimepicker">
              <div class="input-group-text"><i class="fa fa-calendar"></i></div>
            </div>
            -->
          </div>
       </div>
       <div class="form-group">
        <div class="input-group">
          <!-- コードを追加 返信が来たかどうかの確認
          <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
          -->
            <span class="input-group-addon">終了期間</span>
            <input id="date" type="text" name="enddate" class="form-control" placeholder="いつまで yyyy-mm-dd" required/>
            <!-- コードを追加 返信が来たかどうかの確認
            <div class="input-group-append" data-target="#datetimepicker" data-toggle="datetimepicker">
              <div class="input-group-text"><i class="fa fa-calendar"></i></div>
            </div>
            -->
          </div>
       </div>
       <div class="form-group">
        <button type="submit" class="btn btn-danger" name="button" value="search" id="5">検索する</button>
       </div>
    </form>
  </div>
 </div>
 <div class= "col-md-11">
   {% if posts2 %}
   {% for post in posts2 %}
   <div>検索結果</div>
     <div class="white-container">
     <div>{{post["created_at"]}}</div>
     <form class="form-horizontal" action = "{{url_for('users.anary3')}}" method="post">
       <button type="submit" name="user_id" value={{post["user_id"]}}>ユーザー名:{{post["user_id"]}}</button>
      </form>
     <div id="tweet-text">{{post["text"]}}</div>
     <div>
         <span><i class="far fa-heart"></i>  {{post["fav"]}}</span> <span><i class="fas fa-retweet"></i>  {{post["retweet"]}}</span>
         <a class="pull-right" href="https://twitter.com/{{post["user_id"]}}" target="_blank">ユーザーのアカウント</a> -->
     </div>
     </div>
   {% endfor %}
   {% endif %}
 </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/locale/ja.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"></script>
<script type="text/javascript" src="script.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<script>
 {% if profile %}
  // bar chart data
  var barData = {
  labels : [{% for index, row in tweets_df.sort_values(by="created_at", ascending=True).iterrows() %}
                 "{{row['created_at']}}",
             {% endfor %}],
  datasets : [
     {
           label: "Retweets",
           backgroundColor: 'rgba(255, 99, 132, 0.2)',
           borderColor: 'rgba(255,99,132,1)',
           borderWidth:10,
           bezierCurve : false,
           data : [{% for index, row in tweets_df.sort_values(by="created_at", ascending=True).iterrows() %}
                     {{row["retweets"]}},
                   {% endfor %}]
     },{
           label: "Favorites",
           data : [{% for index, row in tweets_df.sort_values(by="created_at", ascending=True).iterrows() %}
                     {{row["fav"]}},
                   {% endfor %}],
           type: 'line',
           borderColor: 'rgb(63, 127, 191)',
     }
     ]
  }
  // draw bar chart
 var mychart = document.getElementById("chart");
 var chart = new Chart(mychart, {
   type:'bar',
   data:barData,
   options: {
       scales: {
         yAxes: [
           {
             ticks: {
               beginAtZero: true,
               min: 0,
               max: 1000
             }
           }
         ]
       }
     }
 });
  {% endif %}
</script>
</body>
</html>